#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

feh --bg-fill ~/.config/bspwm/wallpaper.jpg

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width 2
bspc config focused_border_color \#00FF00
bspc config normal_border_color \#D2D8E0
bspc config window_gap          3

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config top_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config bottom_padding 0

#Custom


# Autostart
$HOME/.screenlayout/screen.sh &
picom &
compton --restore &
$HOME/.config/polybar/launch.sh &
polybar example &
export SXHKDRC="nano ~/.config/sxhkd/sxhkdrc"
