#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Reglas de spawneo de ventanas o apps
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firejail desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#################
##Customization##
#################


# Seguimiento de ventanas con puntero de raton
bspc config focus_follows_pointer true

# Bordeado de esquinas y anulación de borde ventanas
picom --experimental-backends &


# Carga de fondo de escritorio
feh --bg-fill /home/vindicare/Imágenes/fondo.jpg

# Lanzamiento de polybar
~/.config/polybar/./launch.sh
